title: "Daniel SEBABI TUAMINI"
logo: Screenshot_20260330-105936_Gallery.jpg
description: "Administrateur Réseau | Cybersécurité | Interprète en Langue des Signes"
theme: jekyll-theme-minimal
lang: fr
body {
    background-color: #0d1117;
    color: white;
}

a {
    color: #58a6ff;
}

header {
    background-color: #161b22;
}
